# Generated by Django 6.0.3 on 2026-04-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
